services:
  postgres:
    image: postgres:15-alpine
    container_name: payment_postgres
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payment_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: payment_backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/paymentdb
      SUPER_SECRET_TOKEN: your_super_secret_token_here
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - payment_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: payment_frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_SUPER_SECRET_TOKEN: your_super_secret_token_here
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - payment_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  payment_network:
    driver: bridge
